- hosts: all
  become: true
  vars_files:
    - vault/ldap.yml
  vars:
    mongodb_version: "4.4"
    mongodb_storage_dbpath: /data/db
    mongodb_net_bindip: 0.0.0.0
    mongodb_login_host: "{{ hostvars[groups['mongo_master'][0]].ansible_default_ipv4.address }}"
    mongodb_disable_transparent_hugepages: true
    mongodb_net_ssl_mode: disabled
    
    mongodb_security_authorization: enabled
    mongodb_root_admin_name: siteRootAdmin
    mongodb_root_admin_password: "{{ vault_mongodb_users.siteRootAdmin }}"
    mongodb_user_admin_name: siteUserAdmin
    mongodb_user_admin_password: "{{ vault_mongodb_users.siteUserAdmin }}"
    mongodb_root_backup_name: backupuser
    mongodb_root_backup_password: "{{ vault_mongodb_users.backupuser }}"

    mongodb_keyfile_content: |
      8pYcxvCqoe89kcp33KuTtKVf5MoHGEFjTnudrq5BosvWRoIxLowmdjrmUpVfAivh
      CHjqM6w0zVBytAxH1lW+7teMYe6eDn2S/O/1YlRRiW57bWU3zjliW3VdguJar5i9
      Z+1a8lI+0S9pWynbv9+Ao0aXFjSJYVxAm/w7DJbVRGcPhsPmExiSBDw8szfQ8PAU
      2hwRl7nqPZZMMR+uQThg/zV9rOzHJmkqZtsO4UJSilG9euLCYrzW2hdoPuCrEDhu
      Vsi5+nwAgYR9dP2oWkmGN1dwRe0ixSIM2UzFgpaXZaMOG6VztmFrlVXh8oFDRGM0
      cGrFHcnGF7oUGfWnI2Cekngk64dHA2qD7WxXPbQ/svn9EfTY5aPw5lXzKA87Ds8p
      KHVFUYvmA6wVsxb/riGLwc+XZlb6M9gqHn1XSpsnYRjF6UzfRcRR2WyCxLZELaqu
      iKxLKB5FYqMBH7Sqg3qBCtE53vZ7T1nefq5RFzmykviYP63Uhu/A2EQatrMnaFPl
      TTG5CaPjob45CBSyMrheYRWKqxdWN93BTgiTW7p0U6RB0/OCUbsVX6IG3I9N8Uqt
      l8Kc+7aOmtUqFkwo8w30prIOjStMrokxNsuK9KTUiPu2cj7gwYQ574vV3hQvQPAr
      hhb9ohKr0zoPQt31iTj0FDkJzPepeuzqeq8F51HB56RZKpXdRTfY8G6OaOT68cV5
      vP1O6T/okFKrl41FQ3CyYN5eRHyRTK99zTytrjoP2EbtIZ18z+bg/angRHYNzbgk
      lc3jpiGzs1ZWHD0nxOmHCMhU4usEcFbV6FlOxzlwrsEhHkeiununlCsNHatiDgzp
      ZWLnP/mXKV992/Jhu0Z577DHlh+3JIYx0PceB9yzACJ8MNARHF7QpBkhtuGMGZpF
      T+c73exupZFxItXs1Bnhe3djgE3MKKyYvxNUIbcTJoe7nhVMrwO/7lBSpVLvC4p3
      wR700U0LDaGGQpslGtiE56SemgoP

    mongodb_replication_params:
      - {
          host_name: "{{ hostvars[groups['mongo_master'][0]].ansible_default_ipv4.address }}",
          host_port: "{{ mongodb_net_port }}",
          host_type: replica,
          priority: 30,
        }
      - {
          host_name: "{{ hostvars[groups['mongo_replicas'][0]].ansible_default_ipv4.address }}",
          host_port: "{{ mongodb_net_port }}",
          host_type: replica,
          priority: 20,
        }
      - {
          host_name: "{{ hostvars[groups['mongo_replicas'][1]].ansible_default_ipv4.address }}",
          host_port: "{{ mongodb_net_port }}",
          host_type: replica,
          priority: 10,
        }
    mongodb_replication_replset: rs0

    mongodb_users:
      - {
        name: developer,
        password: "{{ vault_mongodb_users.developer }}",
        roles: [{db: "developer", role: "readWrite"}],
        database: developer
    }

    mongodb_oplog_users:
      - {
        user: oplog,
        password: "{{ vault_mongodb_users.oplog }}"
    }

  roles:
    - mongodb-cluster
